### ISSUE TITLE
NV-3. Create update scheduler.

### ISSUE THREAD

**Issue by AKalinins** [msin87/nashvozduh#4]
Create update scheduler to fire getUpdates request every n minutes(seconds?).

**Comment by msin87** [comment]
Lets speak on international russian =))
Обновления бот получает автоматически. У него уже реализован этот механизм, который с заданной периодичностью забирает обновления с сервера. По идее, эта периодичность должна настраиваться. Но это все маловажно. Посмотрим потом, как изменить, если понадобится
